version: "3.8"

services:
    tgbot:
        build:
            dockerfile: Dockerfile
        container_name: tgbot-npm
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            - ENV=${ENV}
        ports:
            - "3000:3000"
        restart: "no"
        networks:
            - default

networks:
  default:
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 10.110.5.0/24
